diff --git a/dev/automated_tests/flutter_test/exception_handling_expectation.txt b/dev/automated_tests/flutter_test/exception_handling_expectation.txt
index a7ec74b22..9623be932 100644
--- a/dev/automated_tests/flutter_test/exception_handling_expectation.txt
+++ b/dev/automated_tests/flutter_test/exception_handling_expectation.txt
@@ -8,8 +8,8 @@ When the exception was thrown, this was the stack:
 <asynchronous suspension>
 #1      .+ \(package:flutter_test[/\\]src[/\\]widget_tester\.dart:[0-9]+:[0-9]+\)
 <<skip until matching line>>
-^\(elided [0-9]+ .+\)$
-
+^\(elided [0-9]+
+<<skip until matching line>>
 The test description was:
 Exception handling in test harness - string
 ════════════════════════════════════════════════════════════════════════════════════════════════════
@@ -27,8 +27,8 @@ When the exception was thrown, this was the stack:
 <asynchronous suspension>
 #1      .+ \(package:flutter_test[/\\]src[/\\]widget_tester\.dart:[0-9]+:[0-9]+\)
 <<skip until matching line>>
-^\(elided [0-9]+ .+\)$
-
+^\(elided [0-9]+
+<<skip until matching line>>
 The test description was:
 Exception handling in test harness - FlutterError
 ════════════════════════════════════════════════════════════════════════════════════════════════════
@@ -49,8 +49,8 @@ When the exception was thrown, this was the stack:
 #[0-9]+ +.+ \(package:flutter_test[/\\]src[/\\]binding.dart:[0-9]+:[0-9]+\)
 #[0-9]+ +.+ \(package:flutter_test[/\\]src[/\\]widget_tester\.dart:[0-9]+:[0-9]+\)
 <<skip until matching line>>
-^\(elided [0-9]+ .+\)$
-
+^\(elided [0-9]+
+<<skip until matching line>>
 The test description was:
 Exception handling in test harness - uncaught Future error
 ════════════════════════════════════════════════════════════════════════════════════════════════════
